# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LBTechTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LBTechTestApp

  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Functions' #google cloud functions
  pod 'Firebase/Core'
  pod 'FirebaseUI', '~> 8.0' #// needs pod 'SDWebImage'

  target 'LBTechTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LBTechTestAppUITests' do
    # Pods for testing
  end

end
